FROM node:16-alpine
# Set the working directory
WORKDIR /app
# Copy package.json and package-lock.json
COPY package* .
# Install dependencies
RUN npm install
# Copy the rest of the application code
COPY . .
# Expose the port the app runs on
CMD ["npm", "run", "dev"]